// <auto-generated />
using System;
using MaracasMusic.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaracasMusic.API.Migrations
{
    [DbContext(typeof(MaracasContext))]
    [Migration("20191024134435_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Maracas.Lib.Models.Artist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("GenreId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            GenreId = 1L,
                            Name = "Shakira"
                        },
                        new
                        {
                            Id = 2L,
                            GenreId = 1L,
                            Name = "Juanes"
                        },
                        new
                        {
                            Id = 3L,
                            GenreId = 2L,
                            Name = "Marc Anthony"
                        },
                        new
                        {
                            Id = 4L,
                            GenreId = 2L,
                            Name = "Grupo Niche"
                        },
                        new
                        {
                            Id = 5L,
                            GenreId = 3L,
                            Name = "Maluma"
                        },
                        new
                        {
                            Id = 6L,
                            GenreId = 3L,
                            Name = "Chino y Nacho"
                        },
                        new
                        {
                            Id = 7L,
                            GenreId = 4L,
                            Name = "Carlos Vives"
                        },
                        new
                        {
                            Id = 8L,
                            GenreId = 5L,
                            Name = "Elvis Crespo"
                        });
                });

            modelBuilder.Entity("Maracas.Lib.Models.Cd", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ArtistId");

                    b.Property<long?>("GenreId");

                    b.Property<string>("Name");

                    b.Property<long>("ProductId");

                    b.Property<long>("ProductTypeId");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Cds");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ArtistId = 1L,
                            GenreId = 1L,
                            Name = "Shakira",
                            ProductId = 1L,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ArtistId = 1L,
                            GenreId = 1L,
                            Name = "El Dorado",
                            ProductId = 2L,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            ArtistId = 2L,
                            GenreId = 1L,
                            Name = "Mi sangre",
                            ProductId = 3L,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            ArtistId = 2L,
                            GenreId = 1L,
                            Name = "Un dia normal",
                            ProductId = 4L,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            ArtistId = 3L,
                            GenreId = 2L,
                            Name = "3.0",
                            ProductId = 5L,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            ArtistId = 3L,
                            GenreId = 2L,
                            Name = "Sigo siendo yo",
                            ProductId = 6L,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            ArtistId = 4L,
                            GenreId = 2L,
                            Name = "Brillantes",
                            ProductId = 7L,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            ArtistId = 4L,
                            GenreId = 2L,
                            Name = "Bonitas y hermosas",
                            ProductId = 8L,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            ArtistId = 5L,
                            GenreId = 3L,
                            Name = "11:11",
                            ProductId = 9L,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            ArtistId = 5L,
                            GenreId = 3L,
                            Name = "F.A.M.E",
                            ProductId = 10L,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            ArtistId = 6L,
                            GenreId = 3L,
                            Name = "Supremo",
                            ProductId = 11L,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            ArtistId = 6L,
                            GenreId = 3L,
                            Name = "Radio universo",
                            ProductId = 12L,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 13L,
                            ArtistId = 7L,
                            GenreId = 4L,
                            Name = "VIVES",
                            ProductId = 13L,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 14L,
                            ArtistId = 7L,
                            GenreId = 4L,
                            Name = "Más + Corazón Profundo",
                            ProductId = 14L,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 15L,
                            ArtistId = 8L,
                            GenreId = 5L,
                            Name = "Suavemente",
                            ProductId = 15L,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 16L,
                            ArtistId = 8L,
                            GenreId = 5L,
                            Name = "Los Monsters",
                            ProductId = 16L,
                            ProductTypeId = 1L
                        });
                });

            modelBuilder.Entity("Maracas.Lib.Models.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Maracas.Lib.Models.Genre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Pop Muziek"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Salsa"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Regueton"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Cumbia"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Cumbia"
                        });
                });

            modelBuilder.Entity("Maracas.Lib.Models.Instrument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("InstrumentTypeId");

                    b.Property<string>("Name");

                    b.Property<long>("ProductId");

                    b.Property<long>("ProductTypeId");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentTypeId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Instruments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            InstrumentTypeId = 1L,
                            Name = "LPM198 Mini Tuneable Conga",
                            ProductId = 17L,
                            ProductTypeId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            InstrumentTypeId = 1L,
                            Name = "Large Wooden Maracas",
                            ProductId = 18L,
                            ProductTypeId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            InstrumentTypeId = 2L,
                            Name = "Vera Cruz Harp",
                            ProductId = 19L,
                            ProductTypeId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            InstrumentTypeId = 2L,
                            Name = "Baja Sexto",
                            ProductId = 20L,
                            ProductTypeId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            InstrumentTypeId = 3L,
                            Name = "Gewa Pan Pipe",
                            ProductId = 21L,
                            ProductTypeId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            InstrumentTypeId = 3L,
                            Name = "Quena Flute",
                            ProductId = 22L,
                            ProductTypeId = 2L
                        });
                });

            modelBuilder.Entity("Maracas.Lib.Models.InstrumentType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("InstrumentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Percussion"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Strings"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Winds"
                        });
                });

            modelBuilder.Entity("Maracas.Lib.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ClientId");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Maracas.Lib.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Foto");

                    b.Property<long?>("OrderId");

                    b.Property<decimal>("Price");

                    b.Property<long>("ProductTypeId");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "CD (ALBUM) |1 disk |Engels|maart 2014",
                            Foto = "CdShakira1",
                            Price = 11m,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Description = "CD (ALBUM) |1 disk |Engels|mei 2017",
                            Foto = "CdShakira2",
                            Price = 10m,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Description = "CD (ALBUM) |1 disk |Spaans|september 2004",
                            Foto = "CdJuanes1",
                            Price = 11m,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Description = "CD (ALBUM) |1 disk |Spaans|mei 2002",
                            Foto = "CdJuanes1",
                            Price = 9m,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Description = "CD (ALBUM) |1 disk |Spaans|juli 2013",
                            Foto = "CdMarcA1",
                            Price = 11m,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 6L,
                            Description = "CD (ALBUM) |1 disk |Spaans|juli 2006 |Verzamelalbum",
                            Foto = "CdMarcA2",
                            Price = 11m,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 7L,
                            Description = "CD (ALBUM) |1 disk |Spaans|juni 1994  |Verzamelalbum",
                            Foto = "CdGrupoN1",
                            Price = 15m,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            Description = "CD (ALBUM) |1 disk |Spaans|november 2015 ",
                            Foto = "CdGrupoN2",
                            Price = 20m,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 9L,
                            Description = "CD (ALBUM) |1 disk |Spaans|mei 2019 ",
                            Foto = "CdMaluma1",
                            Price = 22m,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            Description = "CD (ALBUM) |1 disk |Spaans|mei 2018 ",
                            Foto = "CdMaluma2",
                            Price = 22m,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 11L,
                            Description = "CD (ALBUM) |1 disk |Spaans|October 2011",
                            Foto = "CdChino1",
                            Price = 20m,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 12L,
                            Description = "CD (ALBUM) |1 disk |Spaans|June 23, 2015",
                            Foto = "CdChino2",
                            Price = 18m,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 13L,
                            Description = "CD (ALBUM) |1 disk |Spaans|Nov 10, 2017",
                            Foto = "CdVives1",
                            Price = 18m,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 14L,
                            Description = "CD (ALBUM) |1 disk |Spaans|May 13, 2014",
                            Foto = "CdVives2",
                            Price = 18m,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 15L,
                            Description = "CD (ALBUM) |1 disk |Spaans|april 1998",
                            Foto = "CdElvisC1",
                            Price = 18m,
                            ProductTypeId = 1L
                        },
                        new
                        {
                            Id = 16L,
                            Description = "CD (ALBUM) |1 disk |Spaans|mei 2012",
                            Foto = "CdElvisC2",
                            Price = 20m,
                            ProductTypeId = 1L
                        });
                });

            modelBuilder.Entity("Maracas.Lib.Models.ProductType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("ProductType");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Type = "Cd"
                        },
                        new
                        {
                            Id = 2L,
                            Type = "Instrument"
                        },
                        new
                        {
                            Id = 3L,
                            Type = "Score"
                        });
                });

            modelBuilder.Entity("Maracas.Lib.Models.Score", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ArtistId");

                    b.Property<long?>("GenreId");

                    b.Property<string>("Name");

                    b.Property<long>("ProductId");

                    b.Property<long>("ProductTypeId");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Scores");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ArtistId = 1L,
                            GenreId = 1L,
                            Name = "Whenever, wherever",
                            ProductId = 23L,
                            ProductTypeId = 3L
                        },
                        new
                        {
                            Id = 2L,
                            ArtistId = 1L,
                            GenreId = 1L,
                            Name = "Hips don't Lie",
                            ProductId = 24L,
                            ProductTypeId = 3L
                        },
                        new
                        {
                            Id = 3L,
                            ArtistId = 2L,
                            GenreId = 1L,
                            Name = "La Camisa Negra",
                            ProductId = 25L,
                            ProductTypeId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            ArtistId = 2L,
                            GenreId = 1L,
                            Name = "Juntos",
                            ProductId = 26L,
                            ProductTypeId = 3L
                        },
                        new
                        {
                            Id = 5L,
                            ArtistId = 3L,
                            GenreId = 2L,
                            Name = "Vivir mi Vida",
                            ProductId = 27L,
                            ProductTypeId = 3L
                        },
                        new
                        {
                            Id = 6L,
                            ArtistId = 3L,
                            GenreId = 2L,
                            Name = "Te Conozco Bien",
                            ProductId = 28L,
                            ProductTypeId = 3L
                        },
                        new
                        {
                            Id = 7L,
                            ArtistId = 4L,
                            GenreId = 2L,
                            Name = "Tapanco El Hueco",
                            ProductId = 29L,
                            ProductTypeId = 3L
                        },
                        new
                        {
                            Id = 8L,
                            ArtistId = 4L,
                            GenreId = 2L,
                            Name = "El Amor Vendra",
                            ProductId = 30L,
                            ProductTypeId = 3L
                        },
                        new
                        {
                            Id = 9L,
                            ArtistId = 5L,
                            GenreId = 3L,
                            Name = "Felices Los 4",
                            ProductId = 31L,
                            ProductTypeId = 3L
                        },
                        new
                        {
                            Id = 10L,
                            ArtistId = 5L,
                            GenreId = 3L,
                            Name = "Corazòn",
                            ProductId = 32L,
                            ProductTypeId = 3L
                        },
                        new
                        {
                            Id = 11L,
                            ArtistId = 6L,
                            GenreId = 3L,
                            Name = "Andas en mi Cabeza",
                            ProductId = 33L,
                            ProductTypeId = 3L
                        },
                        new
                        {
                            Id = 12L,
                            ArtistId = 6L,
                            GenreId = 3L,
                            Name = "Mi Niña Bonita",
                            ProductId = 34L,
                            ProductTypeId = 3L
                        },
                        new
                        {
                            Id = 13L,
                            ArtistId = 7L,
                            GenreId = 4L,
                            Name = "Déjame Entrar",
                            ProductId = 35L,
                            ProductTypeId = 3L
                        },
                        new
                        {
                            Id = 14L,
                            ArtistId = 7L,
                            GenreId = 4L,
                            Name = "Carito",
                            ProductId = 36L,
                            ProductTypeId = 3L
                        },
                        new
                        {
                            Id = 15L,
                            ArtistId = 8L,
                            GenreId = 5L,
                            Name = "Suavemente",
                            ProductId = 37L,
                            ProductTypeId = 3L
                        },
                        new
                        {
                            Id = 16L,
                            ArtistId = 8L,
                            GenreId = 5L,
                            Name = "Pintame",
                            ProductId = 38L,
                            ProductTypeId = 3L
                        });
                });

            modelBuilder.Entity("Maracas.Lib.Models.Artist", b =>
                {
                    b.HasOne("Maracas.Lib.Models.Genre", "Genre")
                        .WithMany("Artists")
                        .HasForeignKey("GenreId");
                });

            modelBuilder.Entity("Maracas.Lib.Models.Cd", b =>
                {
                    b.HasOne("Maracas.Lib.Models.Artist", "Artist")
                        .WithMany("Cds")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Maracas.Lib.Models.Genre", "Genre")
                        .WithMany("Cds")
                        .HasForeignKey("GenreId");

                    b.HasOne("Maracas.Lib.Models.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Maracas.Lib.Models.Instrument", b =>
                {
                    b.HasOne("Maracas.Lib.Models.InstrumentType", "InstrumentType")
                        .WithMany("Instruments")
                        .HasForeignKey("InstrumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Maracas.Lib.Models.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Maracas.Lib.Models.Order", b =>
                {
                    b.HasOne("Maracas.Lib.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Maracas.Lib.Models.Product", b =>
                {
                    b.HasOne("Maracas.Lib.Models.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("Maracas.Lib.Models.Score", b =>
                {
                    b.HasOne("Maracas.Lib.Models.Artist", "Artist")
                        .WithMany("Scores")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Maracas.Lib.Models.Genre", "Genre")
                        .WithMany("Scores")
                        .HasForeignKey("GenreId");

                    b.HasOne("Maracas.Lib.Models.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
