// <auto-generated />
using System;
using MaracasMusic.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaracasMusic.API.Migrations
{
    [DbContext(typeof(MaracasContext))]
    partial class MaracasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Maracas.Lib.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GenreId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreId = 1,
                            Name = "Geen artiest"
                        },
                        new
                        {
                            Id = 2,
                            GenreId = 2,
                            Name = "Shakira"
                        },
                        new
                        {
                            Id = 3,
                            GenreId = 2,
                            Name = "Juanes"
                        },
                        new
                        {
                            Id = 4,
                            GenreId = 3,
                            Name = "Marc Anthony"
                        },
                        new
                        {
                            Id = 5,
                            GenreId = 3,
                            Name = "Grupo Niche"
                        },
                        new
                        {
                            Id = 6,
                            GenreId = 4,
                            Name = "Maluma"
                        },
                        new
                        {
                            Id = 7,
                            GenreId = 4,
                            Name = "Chino y Nacho"
                        },
                        new
                        {
                            Id = 8,
                            GenreId = 5,
                            Name = "Carlos Vives"
                        },
                        new
                        {
                            Id = 9,
                            GenreId = 6,
                            Name = "Elvis Crespo"
                        });
                });

            modelBuilder.Entity("Maracas.Lib.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Maracas.Lib.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Geen genre"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pop Muziek"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Salsa"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Regueton"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cumbia"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Merengue"
                        });
                });

            modelBuilder.Entity("Maracas.Lib.Models.InstrumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("InstrumentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Geen instrumentType"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Percussion"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Strings"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Winds"
                        });
                });

            modelBuilder.Entity("Maracas.Lib.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId");

                    b.Property<DateTime>("DateOrder");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Maracas.Lib.Models.OrderDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Aantal");

                    b.Property<string>("Name");

                    b.Property<int>("OrderId");

                    b.Property<int>("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Maracas.Lib.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtistId");

                    b.Property<string>("Description");

                    b.Property<string>("Foto");

                    b.Property<int?>("GenreId");

                    b.Property<int>("InstrumentTypeId");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<int>("ProductTypeId");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("GenreId");

                    b.HasIndex("InstrumentTypeId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 2,
                            Description = "CD (ALBUM) |1 disk |Engels|maart 2014",
                            Foto = "CdShakira1.jpg",
                            GenreId = 2,
                            InstrumentTypeId = 1,
                            Price = 11m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 2,
                            Description = "CD (ALBUM) |1 disk |Engels|mei 2017",
                            Foto = "CdShakira2.jpg",
                            GenreId = 2,
                            InstrumentTypeId = 1,
                            Price = 10m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 3,
                            Description = "CD (ALBUM) |1 disk |Spaans|september 2004",
                            Foto = "CdJuanes1.jpg",
                            GenreId = 2,
                            InstrumentTypeId = 1,
                            Price = 11m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            ArtistId = 3,
                            Description = "CD (ALBUM) |1 disk |Spaans|mei 2002",
                            Foto = "CdJuanes2.jpg",
                            GenreId = 2,
                            InstrumentTypeId = 1,
                            Price = 9m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            ArtistId = 4,
                            Description = "CD (ALBUM) |1 disk |Spaans|juli 2013",
                            Foto = "CdMarcA1.jpg",
                            GenreId = 3,
                            InstrumentTypeId = 1,
                            Price = 11m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            ArtistId = 4,
                            Description = "CD (ALBUM) |1 disk |Spaans|juli 2006 |Verzamelalbum",
                            Foto = "CdMarcA2.jpg",
                            GenreId = 3,
                            InstrumentTypeId = 1,
                            Price = 11m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 7,
                            ArtistId = 5,
                            Description = "CD (ALBUM) |1 disk |Spaans|juni 1994  |Verzamelalbum",
                            Foto = "CdGrupoN1.jpg",
                            GenreId = 3,
                            InstrumentTypeId = 1,
                            Price = 15m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            ArtistId = 5,
                            Description = "CD (ALBUM) |1 disk |Spaans|november 2015 ",
                            Foto = "CdGrupoN2.jpg",
                            GenreId = 3,
                            InstrumentTypeId = 1,
                            Price = 20m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 9,
                            ArtistId = 6,
                            Description = "CD (ALBUM) |1 disk |Spaans|mei 2019 ",
                            Foto = "CdMaluma1.jpg",
                            GenreId = 4,
                            InstrumentTypeId = 1,
                            Price = 22m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            ArtistId = 6,
                            Description = "CD (ALBUM) |1 disk |Spaans|mei 2018 ",
                            Foto = "CdMaluma2.jpg",
                            GenreId = 4,
                            InstrumentTypeId = 1,
                            Price = 22m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 11,
                            ArtistId = 7,
                            Description = "CD (ALBUM) |1 disk |Spaans|October 2011",
                            Foto = "CdChino1.jpg",
                            GenreId = 4,
                            InstrumentTypeId = 1,
                            Price = 20m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 12,
                            ArtistId = 7,
                            Description = "CD (ALBUM) |1 disk |Spaans|June 23, 2015",
                            Foto = "CdChino2.jpg",
                            GenreId = 4,
                            InstrumentTypeId = 1,
                            Price = 18m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 13,
                            ArtistId = 8,
                            Description = "CD (ALBUM) |1 disk |Spaans|Nov 10, 2017",
                            Foto = "CdVives1.jpg",
                            GenreId = 5,
                            InstrumentTypeId = 1,
                            Price = 18m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 14,
                            ArtistId = 8,
                            Description = "CD (ALBUM) |1 disk |Spaans|May 13, 2014",
                            Foto = "CdVives2.jpg",
                            GenreId = 5,
                            InstrumentTypeId = 1,
                            Price = 18m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 15,
                            ArtistId = 9,
                            Description = "CD (ALBUM) |1 disk |Spaans|april 1998",
                            Foto = "CdElvisC1.jpg",
                            GenreId = 6,
                            InstrumentTypeId = 1,
                            Price = 18m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 16,
                            ArtistId = 9,
                            Description = "CD (ALBUM) |1 disk |Spaans|mei 2012",
                            Foto = "CdElvisC2.jpg",
                            GenreId = 6,
                            InstrumentTypeId = 1,
                            Price = 20m,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 17,
                            ArtistId = 1,
                            Description = "Finish: Natural - Siam Oak drum shell with natural head - Head: Ø 4.5' - Approx. 28 cm high - Mini Comfort Curve II Rims",
                            Foto = "instrumentPerc1.jpg",
                            GenreId = 1,
                            InstrumentTypeId = 2,
                            Price = 60m,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 18,
                            ArtistId = 1,
                            Description = "Simple wooden percussion instrument, deliverd in pairs",
                            Foto = "instrumentPerc2.jpg",
                            GenreId = 1,
                            InstrumentTypeId = 2,
                            Price = 20m,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 19,
                            ArtistId = 1,
                            Description = "",
                            Foto = "instrumentString1.jpg",
                            GenreId = 1,
                            InstrumentTypeId = 3,
                            Price = 50m,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 20,
                            ArtistId = 1,
                            Description = "RoseWood back, glossy finish, hand crafted",
                            Foto = "instrumentString2.jpg",
                            GenreId = 1,
                            InstrumentTypeId = 3,
                            Price = 470m,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 21,
                            ArtistId = 1,
                            Description = "Hand crafted, made of Bamboo, pure tuning",
                            Foto = "instrumentWind1",
                            GenreId = 1,
                            InstrumentTypeId = 4,
                            Price = 20m,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 22,
                            ArtistId = 1,
                            Description = "Hand crafted, made of plum wood",
                            Foto = "instrumentWind2",
                            GenreId = 1,
                            InstrumentTypeId = 4,
                            Price = 45m,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 23,
                            ArtistId = 2,
                            Description = "Shakira sheet music - Song: Whenever, Wherever",
                            Foto = "scoreSha1.jpg",
                            GenreId = 2,
                            InstrumentTypeId = 1,
                            Price = 9.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 24,
                            ArtistId = 2,
                            Description = "Shakira sheet music - Song: Hips don't Lie",
                            Foto = "scoreSha2.jpg",
                            GenreId = 2,
                            InstrumentTypeId = 1,
                            Price = 9.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 25,
                            ArtistId = 3,
                            Description = "Juanes sheet music - Song: La Camisa Negra",
                            Foto = "scoreJua1.jpg",
                            GenreId = 2,
                            InstrumentTypeId = 1,
                            Price = 9.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 26,
                            ArtistId = 3,
                            Description = "Juanes sheet music - Song: Juentos",
                            Foto = "scoreJua2.jpg",
                            GenreId = 2,
                            InstrumentTypeId = 1,
                            Price = 9.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 27,
                            ArtistId = 4,
                            Description = "Marc Anthony sheet music - Song: Vivir mi Vida",
                            Foto = "scoreMar1.jpg",
                            GenreId = 3,
                            InstrumentTypeId = 1,
                            Price = 9.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 28,
                            ArtistId = 4,
                            Description = "Marc Anthony sheet music - Song: Te Conozco Bien",
                            Foto = "scoreMar2.jpg",
                            GenreId = 3,
                            InstrumentTypeId = 1,
                            Price = 9.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 29,
                            ArtistId = 5,
                            Description = "Grupo Niche sheet music - Song: Tapanco El Hueco",
                            Foto = "scoreGru1.jpg",
                            GenreId = 3,
                            InstrumentTypeId = 1,
                            Price = 9.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 30,
                            ArtistId = 5,
                            Description = "Grupo Niche - Song: El Amor Vendra",
                            Foto = "scoreGru2.jpg",
                            GenreId = 3,
                            InstrumentTypeId = 1,
                            Price = 9.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 31,
                            ArtistId = 6,
                            Description = "Maluma sheet music - Song: Felices los 4",
                            Foto = "scoreMal1.jpg",
                            GenreId = 4,
                            InstrumentTypeId = 1,
                            Price = 9.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 32,
                            ArtistId = 6,
                            Description = "Maluma sheet music - Song: Corazòn",
                            Foto = "scoreMal2.jpg",
                            GenreId = 4,
                            InstrumentTypeId = 1,
                            Price = 9.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 33,
                            ArtistId = 7,
                            Description = "Chino y Nacho sheet music - Song: Andas en mi Cabeza",
                            Foto = "scoreChi1.jpg",
                            GenreId = 4,
                            InstrumentTypeId = 1,
                            Price = 9.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 34,
                            ArtistId = 7,
                            Description = "Chino y Nacho sheet music - Song: Mi Niña Bonita",
                            Foto = "scoreChi2.jpg",
                            GenreId = 4,
                            InstrumentTypeId = 1,
                            Price = 9.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 35,
                            ArtistId = 8,
                            Description = "Carlos Vives - Song: Déjame Entrar",
                            Foto = "scoreCar1.jpg",
                            GenreId = 5,
                            InstrumentTypeId = 1,
                            Price = 9.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 36,
                            ArtistId = 8,
                            Description = "Carlos Vives sheet music - Song: Carito",
                            Foto = "scoreCar2.jpg",
                            GenreId = 5,
                            InstrumentTypeId = 1,
                            Price = 9.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 37,
                            ArtistId = 9,
                            Description = "Elvis Crespo sheet music - Song: Suavemente",
                            Foto = "scoreElv1.jpg",
                            GenreId = 6,
                            InstrumentTypeId = 1,
                            Price = 9.99m,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 38,
                            ArtistId = 9,
                            Description = "Elvis Crespo sheet music - Song: Pintame",
                            Foto = "scoreElv2.jpg",
                            GenreId = 6,
                            InstrumentTypeId = 1,
                            Price = 9.99m,
                            ProductTypeId = 3
                        });
                });

            modelBuilder.Entity("Maracas.Lib.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cd"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Instrument"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Score"
                        });
                });

            modelBuilder.Entity("Maracas.Lib.Models.Artist", b =>
                {
                    b.HasOne("Maracas.Lib.Models.Genre", "Genre")
                        .WithMany("Artists")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Maracas.Lib.Models.Order", b =>
                {
                    b.HasOne("Maracas.Lib.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Maracas.Lib.Models.OrderDetails", b =>
                {
                    b.HasOne("Maracas.Lib.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Maracas.Lib.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Maracas.Lib.Models.Product", b =>
                {
                    b.HasOne("Maracas.Lib.Models.Artist", "Artist")
                        .WithMany("Products")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Maracas.Lib.Models.Genre", "Genre")
                        .WithMany("Products")
                        .HasForeignKey("GenreId");

                    b.HasOne("Maracas.Lib.Models.InstrumentType", "InstrumentType")
                        .WithMany("Products")
                        .HasForeignKey("InstrumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Maracas.Lib.Models.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
